apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-044ef7bdb7e2bc6c0

---
apiVersion: v1
kind: PersistantVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" #Empty string must be explicity set otherwise default storageclass will be set
  volumeName: ebs-static
  accessModes:
    -Readwriteonce
  resources:
    requests:
      storage: 15Gi