apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-demonstrate-environments-ariables
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: COURSE
      value: "kubernets"
    - name: TRAINER
      value: "HARSHA"
